package AoC_2025.day07.a;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class LightReflexionTest {
    private final String short_example = """
                   .......S.......
                   ...............
                   .......^.......
                   ...............
                   ......^.^......
                   ...............
                   .....^.^.^.....
                   ...............
                   ....^.^...^....
                   ...............
                   ...^.^...^.^...
                   ...............
                   ..^...^.....^..
                   ...............
                   .^.^.^.^.^...^.
                   ...............
    """;

    @Test
    public void main_test() {
        assertThat(Main.main()).isEqualTo(1546);
    }


    @Test
    public void should_solve_example_case() {
        assertThat(LightEngine.build(short_example).getAppliedReflexions()).isEqualTo(21);
    }


}
