package AoC_2025.day07.b;

import AoC_2025.day07.architecture.Solver;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class LightReflexionTest {
    private final String short_example = """
                   .......S.......
                   ...............
                   .......^.......
                   ...............
                   ......^.^......
                   ...............
                   .....^.^.^.....
                   ...............
                   ....^.^...^....
                   ...............
                   ...^.^...^.^...
                   ...............
                   ..^...^.....^..
                   ...............
                   .^.^.^.^.^...^.
                   ...............
    """;

    @Test
    public void main_test() {
        assertThat(Main.main()).isEqualTo(13883459503480L);
    }



    @Test
    public void should_solve_example_case() {
        assertThat(Solver.with(LightWorld::initialize, short_example.lines()).solveA()).isEqualTo(40);
    }


}
