package AoC_2025.day07.b;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class RangesTest {
    private final String short_example = """
                   .......S.......
                   ...............
                   .......^.......
                   ...............
                   ......^.^......
                   ...............
                   .....^.^.^.....
                   ...............
                   ....^.^...^....
                   ...............
                   ...^.^...^.^...
                   ...............
                   ..^...^.....^..
                   ...............
                   .^.^.^.^.^...^.
                   ...............
    """;

    @Test
    public void should_solve_example_case() {
        assertThat(new LightEngine(short_example).getResult()).isEqualTo(40);
    }


}
